@startuml 手配データ作成フロー

title 手配データ作成フロー
skinparam monochrome true

partition 手配データ作成excel {
    "データ読込" --> "商品別 不足数 集計"

    "商品別 不足数 集計" --> "発注数量決定シート"

    if "手配不可事由"
            --> [あり]"手配保留リスト"
    else
            if "6ケタ 登録"
                --> [あり] "Magic読込用ファイル"
            else
                --> [なし] "手入力用リスト"
        end if 
    end if
    
}

"Amazon_棚なしピッキングシート" --> [ファイル読込]"データ読込"
"楽天_棚なしピッキングシート" --> [ファイル読込]"データ読込"
"Yahoo_棚なしピッキングシート" --> [ファイル読込]"データ読込"
"Amazon卸ピッキングシート"--> [ファイル読込]"データ読込"

Partition "新 Magic" {

    "Magic読込用ファイル" -down-> "Magic読込"
    note right
        必要項目
            倉庫番号 180/187
            6ケタ
            数量
        ※ 他に必要なデータはMagicが
        商品マスタ・仕入先マスタから引っ張る
    end note

    "Magic読込" -down-> "発注データ作成"
        
    "手入力用リスト" --> "Magic手入力"
    note left
            手入力でMagicへ入力
                仕入先
                商品名
                JAN
                数量
                原価
    end note


    "Magic手入力" --> "発注データ作成"

    "定期発注 データ読込" --> "発注データ作成"

    "発注データ作成" --> "手配書起票"
    "手配書テンプレート" -left-> "手配書起票"

}

Partition "起案サブシステム" {
    "起案" --> "定期発注 データ読込"
}

"起案" -up-> [在庫数 参照] "在庫マスタ"
"在庫マスタ" --> "起案"

partition 商魂 {

    "商品マスタ" --> "発注データ作成"
    "仕入先マスタ" --> "発注データ作成"

}

"仕入先マスタ" -right-> "商品マスタ"
--> [6ケタ・ロット数]"発注数量決定シート"

note left
    ロット数は商魂合わせる？
     -> 180番手配は基本ロット手配ではない
     JAN分の仕入先データが要る
end note

partition 発注用商品情報 {
    
    "商品情報" -down-> [登なし仕入先]"発注数量決定シート" 

    note right
        発注用商品情報
            廃番や手配不可の情報が商魂と一致していない
            仕入先コード入ってない
    end note



}

Partition "Faxサーバ" {

    "手配書起票" --> "FAX手配書作成"
    --> 仕入先FAX
}

Partition "仕入先 企業" {

    "仕入先FAX" -->  "受注"
    "手配書起票" --> [EDIでデータ発注]"受注"
}

@enduml