@startuml build_purchase_data

title 手配フロー

skinparam monochrome true

partition 手配データ作成excel {
    "データ読込" --> "商品別 依頼数 集計"

    "商品別 依頼数 集計" --> "発注数量決定シート"

    if "手配不可事由"
            --> [あり]"手配保留リスト"
    else
            if "6ケタ 登録"
                --> [あり] "一括読込用ファイル"
            else
                --> [なし] "手入力用リスト"
        end if 
    end if
    
}

"Amazon_棚なしピッキングシート" --> [ファイル読込]"データ読込"
"楽天_棚なしピッキングシート" --> [ファイル読込]"データ読込"
"Yahoo_棚なしピッキングシート" --> [ファイル読込]"データ読込"
"Amazon卸ピッキングシート"--> [ファイル読込]"データ読込"

Partition "発注システム" {

    "一括読込用ファイル" -down-> "発注システム読込"
    note right
        必要項目
            倉庫番号 180/187
            6ケタ
            数量
            配達・引取区分
            担当者コード
        ※ 他に必要なデータは発注システムが
        商品マスタ・仕入先マスタから引っ張る
    end note

    "発注システム読込" -down-> "発注データ作成"
        
    "手入力用リスト" --> "発注システム手入力"
    note right
            手入力で発注システムへ入力
                仕入先
                商品名
                JAN
                数量
                原価
    end note


    "発注システム手入力" --> "発注データ作成"

    "定期発注データ読込" --> "発注データ作成"

    "発注データ作成" --> "手配書起票"
    "手配書テンプレート" -left-> "手配書起票"

}

partition 商魂 {

    "商品マスタ" --> "発注データ作成"
    "仕入先マスタ" --> "発注データ作成"
    商品マスタ --> 在庫マスタ
}


Partition "起案サブシステム" {
    "在庫監視" -up-> [在庫数 参照] "在庫マスタ" 
    "在庫監視" -->  "起案"
}

    "起案" --> "商品部 手配"
    --> 定期発注データ読込

"仕入先マスタ" -left-> "商品マスタ"
--> [6ケタ・ロット数]"発注数量決定シート"

note Left
     商魂のロット数を参考に表示
     廃番、手配済未入荷など発注保留を判定
     手配数量を決定して入力
end note

partition 発注用商品情報ブック {
    
    "商品情報" -down-> [登なし仕入先]"発注数量決定シート" 
}

Partition "入庫データベース" {
    発注データ作成 --> 入庫待ちデータ
}

Partition "Faxサーバ" {

    "手配書起票" --> [HC定番のみ]"FAX手配書ファイル出力"
}

Partition "仕入先 企業" {

    "FAX手配書ファイル出力" -->  "受注"
    '"手配書起票" --> [EDIでデータ発注]"受注"'
    --> 商品準備
    --> 出荷
}

Partition "第三倉庫" {
    手配書起票 --> FAX用手配書 Excelファイル出力
    -left-> 印刷
    -down-> FAX
    -left-> 受注
}

Partition "管理部" {
    FAX --> 引取依頼
    --> 引取
    -left-> [市内メーカー 引取]商品準備
    -right-> 引取
    引取 --> 検品
    出荷 --> [配達・運送便]荷受
}

-> 検品
検品 -up-> 入庫待ちデータ

Partition "物流部" {

    検品 -> 格納

}

@enduml