@startuml build_purchase_data

title 受注～出荷フロー
skinparam monochrome true

partition "クロスモール" {
    "受注データ取得" --> "送り状用CSV生成"
    "受注データ取得" --> "ピッキングCSV生成"
    "受注データ取得" --> "納品書生成"

}

"Amazon" --> "受注データ取得"
"楽天" --> "受注データ取得"
"Yahoo!" --> "受注データ取得"

Amazonベンダーセントラル --> "xls POファイル"
--> "xlsm Amazon卸"
--> "棚なしピッキングデータ"

"xlsm Amazon卸" --> "棚有りピッキングデータ"

"xlsm Amazon卸" --> [読み書き]"xlsx 連番記録ファイル"

"送り状用CSV生成" --> "佐川ビズロジ用CSVダウンロード"
--> "佐川e飛伝システム"

"送り状用CSV生成" --> "ヤマトB2用CSVダウンロード"
--> "ヤマトB2システム"

"納品書生成" --> "納品書印刷"
--> "振分"
--> "佐川送り状発行"
--> "梱包"

"振分" --> "ヤマト送り状発行" 
"ヤマトB2システム" --> "ヤマト送り状発行"
--> "梱包"

"振分" --> "ネコポス送り状発行" 
"ヤマトB2システム" --> "ネコポス送り状発行" 
--> "梱包"


"佐川e飛伝システム" --> "佐川送り状発行"

"ピッキングCSV生成" --> "ピッキングデータ用CSVダウンロード"
--> "xmlt ピッキングデータ作成"
--> "棚有りピッキングデータ"
--> "電算室 提出"
--> "ハンディ用ピッキングデータ作成"
--> "ピッキング"
--> [ピッキングした商品]"振分"

"ピッキングデータ用CSVダウンロード" --> "xlsm 受注チェックリスト生成"
--> "楽天ハンディ用データ"

"電算室 提出" --> "売上計上"
"電算室 提出" --> "出荷指示データ"

"xmlt ピッキングデータ作成" --> "棚なしピッキングデータ"
--> "手配依頼チェック"
--> "xlsm 手配データ作成"
--> "商品手配"
--> "入荷"
--> "振分"

"手配依頼チェック" --> "xlsm ロゴス発注CSV作成"
--> "商品手配"

"xlsm 手配データ作成" -up-> [参照]"xlsm 発注用商品情報"
"xlsm 手配データ作成" -up-> [参照]"商魂"


"xmlt ピッキングデータ作成" -up-> [参照]"商魂"
"xmlt ピッキングデータ作成" -up-> [参照]"xls セット商品リスト"

"梱包" --> [チェック]"楽天ハンディ用データ"

"梱包" --> "出荷"
--> "集荷"

"集荷" --> "各運送会社 送り状番号追跡"

"出荷" --> [SLIMS処理]"出荷指示データ"


"ヤマトB2システム" --> "送り状番号出力"
"佐川e飛伝システム" --> "送り状番号出力"

partition "クロスモール" {
    "送り状番号出力" --> "出荷通知用CSV生成" 
}

"出荷通知用CSV生成" --> "出荷通知用CSVダウンロード"
--> "xlsm 出荷確認ファイル作成.xlsm"
--> "配送でPon!"
--> "各運送会社 送り状番号追跡"


"出荷通知用CSVダウンロード" --> "出荷通知アップロード"

"配送でPon!" --> "出荷通知アップロード"

"出荷通知アップロード" --> "Amazon出荷通知"
"出荷通知アップロード" --> "楽天出荷通知"
"出荷通知アップロード" --> "Yahoo出荷通知"

"集荷"-->"集荷担当営業所へ"

@enduml