@startuml purchase_flow

[-> Amazon-a -> 

Amazon-a -> APS
楽天-a -> RPS
ヤフー-a -> 手入力貼り付け

ピッキング取込 -> 商品情報チェック

FAX用手配書 ->] 仕入先へFAX
センター用手配書 -> 在庫マスター確認 :電算室 提出
在庫マスター確認 -> 発注入力 : 電算室から発注担当へ伝票移動
発注入力 -> 商魂 : WEB商魂の発注履歴、当社伝の起票
商魂 -> 入庫マスター : 入庫待ちデータ作成 

発注入力 -> 管理部 : 引取依頼

@enduml